### ISSUE TITLE
Live Update

### ISSUE THREAD

**Issue by puhuang** [Okeanos/yii2-chartist#1]
I am going to use Chartist in my project to show the chart. I want to know how to make it to be live view   or refreshing after new record is add.

**Comment by Okeanos** [comment]
You may want to check the [official documentation](http://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update), I can't help with that. Alternatively, ask the question [here](https://github.com/gionkunz/chartist-js).
